services:
  baoounao-backend:
    build: .
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    network_mode: worknet
    restart: unless-stopped
    ports:
      - ${HOST_PORT}:${API_PORT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - API_PORT=${API_PORT}
      - IMAGE=${IMAGE}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - HOST_PORT=${HOST_PORT}
      - URL_EMAIL=${URL_EMAIL}
      - URL_REDIRECT=${URL_REDIRECT}
      - PROPOSAL_LIMIT=${PROPOSAL_LIMIT}
      - VOTES_LIMIT=${VOTES_LIMIT}
      - S3_ACESS_KEY=${S3_ACESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - TZ=America/Sao_Paulo