INSERT INTO cycle_entity(title,start_date,finish_date,created_at) VALUES ('2023/1','2023-07-05', '2023-12-05','2023-03-18');
INSERT INTO cycle_entity(title,start_date,finish_date,created_at) VALUES ('2024/2','2024-08-02', '2024-12-22','2024-03-01');
INSERT INTO category_entity(title,created_at,active) VALUES ('Infraestrutura','2023-03-14',true);
INSERT INTO category_entity(title,created_at,active) VALUES ('Ensino','2023-03-14',true);
INSERT INTO category_entity(title,created_at,active) VALUES ('Alimentação','2023-03-14',true);
INSERT INTO category_entity(title,created_at,active) VALUES ('Transporte','2023-03-14',true);
INSERT INTO user_entity(name,email,type,password,active,created_at) VALUES ('Felipe','soares.felipe200@gmail.com','TAE','$2a$10$9ZAXMak48N5PPj6YINuycOhuhTtlRLPBJMlYFyzAYRDpGzNE4X0se',true,'2024-03-14');
INSERT INTO user_entity(name,email,type,password,active,created_at) VALUES ('Elisabete','elisabete@teste.com','DOCENTE','$2a$10$9ZAXMak48N5PPj6YINuycOhuhTtlRLPBJMlYFyzAYRDpGzNE4X0se',true,'2024-03-14');
INSERT INTO user_entity(name,email,type,password,active,created_at) VALUES ('Hyan','hyan@teste.com','3','ESTUDANTE',true,'2024-03-14');
INSERT INTO user_entity(name,email,type,password,active,created_at) VALUES ('Cristian','cristian@teste.com','ESTUDANTE','1234',true,'2024-03-14');
INSERT INTO user_entity(name,email,type,password,active,created_at) VALUES ('Josimar','josimar@teste.com','DOCENTE','springehbao',true,'2024-03-19');
insert into  proposal_entity(title,description,likes,situation,active,created_at,video_url,user_entity_id,cycle_entity_id,category_entity_id) VALUES ("Modernização dos Laboratórios de Informática","Proposta para atualizar equipamentos e software dos laboratórios de informática visando melhorar a qualidade do ensino prático em disciplinas de tecnologia.",0,"APPROVED",true,"2023-03-21","http://amigos/teste",1,1,1);
insert into  proposal_entity(title,description,likes,situation,active,created_at,video_url,user_entity_id,cycle_entity_id,category_entity_id) VALUES ("Reforma dos Espaços de Convivência Estudantil","Projeto para revitalizar áreas comuns da faculdade, proporcionando espaços mais confortáveis e adequados para interação entre os alunos.",0,"APPROVED",true,"2023-03-21","http://amigos/teste",1,1,2);
insert into  proposal_entity(title,description,likes,situation,active,created_at,video_url,user_entity_id,cycle_entity_id,category_entity_id) VALUES ("Ampliação da Biblioteca Universitária","Iniciativa para expandir o acervo e modernizar as instalações da biblioteca, promovendo um ambiente propício para estudos e pesquisa.",0,"APPROVED",true,"2023-03-21","http://amigos/teste",1,1,3);
INSERT INTO voting_entity(user_entity_id,proposal_entity_id,created_at) VALUES(1,1,'2024-03-18');
INSERT INTO voting_entity(user_entity_id,proposal_entity_id,created_at) VALUES(1,2,'2024-03-18');
INSERT INTO role_entity(name) VALUES ('ROLE_ADMINISTRATOR');
INSERT INTO role_entity(name) VALUES ('ROLE_USER');
INSERT INTO user_roles(role_id,user_id) VALUES (1,1);
INSERT INTO user_roles(role_id,user_id) VALUES (2,1);
